### ISSUE TITLE
Critical: malicious eval crashes rudybot

### ISSUE THREAD

**Issue by ToBeFree** [offby1/rudybot#35] opened 2016-09-08 07:14 UTC
09:13:24 <ToBeCloud> eval (for ([i (in-naturals)])(displayln "reproduce the bug"))
09:13:25 <rudybot> your sandbox is ready
09:13:28 ⇐ rudybot quit (~luser@ec2-52-8-12-207.us-west-1.compute.amazonaws.com) Remote host closed the connection

**Comment by offby1** [comment] 2016-09-08 14:38
I'm reasonably sure that the problem is: rudybot consumes a lot of memory before the various sandbox limits (time and memory usage(!)) apply, and the OOM killer kills it.

My "fix" is to simply add some swap -- there hadn't been any before, and memory is pretty tight on that el-cheapo ec2 instance on which rudybot runs.

Another idea would be to further reduce [the various sandbox limits](https://github.com/offby1/rudybot/blob/master/sandboxes.rkt#L15).

The lingering mystery: of the three or four times that I've seen this happen, only one or two of them actually provoked the kernel's "oom killer"; in the other cases, all I saw in `/var/log/messages` was
````
Sep  8 07:07:03 ip-10-0-0-142 init: rudybot main process (23851) killed by ABRT signal
Sep  8 07:07:03 ip-10-0-0-142 init: rudybot main process ended, respawning
````

**Comment by offby1** [comment] 2016-09-09 13:54
I'm closing this, because adding swap prevented it from recurring.

**Closed by offby1** 2016-09-09 13:54 UTC
